t5629b.scala:36: warning: This catches all Throwables. If this is really intended, use `case x : Throwable` to clear this warning.
  try { pf(1) } catch { case x => println(x) }
                             ^
one warning found
=== pf(1):
MySmartPF.apply entered...
newPF.applyOrElse entered...
default
scala.MatchError: () (of class scala.runtime.BoxedUnit)
=== pf(42):
MySmartPF.apply entered...
newPF.applyOrElse entered...
ok
=== done
